NUM_OF_DECKS = 6
NUM_OF_CARDS = 312

CARD_RANKS = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King", "Ace"]
CARD_SUITS = ["Clubs", "Diamonds", "Hearts", "Spades"]
COURT_CARDS = CARD_RANKS[9:12]
NUMBER_CARDS = CARD_RANKS[:9]
ACE_RANK = CARD_RANKS[-1]

PUSH = "PUSH"
WON = "WON"
LOST = "LOST"
BUST = "BUST"
IN_PLAY = "IN PLAY"
BLACKJACK = "BLACKJACK"
PLAYER_BUSTED = "PLAYER BUSTED"
DEALER_BUSTED = "DEALER BUSTED"
DEALER_BLACKJACK = "DEALER BLACKJACK"
PLAYER_BLACKJACK = "PLAYER BLACKJACK"

STAND = "STAND"
HIT = "HIT"
DOUBLE_DOWN = "DOUBLE DOWN"
SPLIT = "SPLIT"
SURRENDER = "SURRENDER"